# Makefile for AT32 hardware test on FNIRSI 2C53T
# Minimal build: clock init + power hold + backlight + LCD

PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
NANO_SPECS := $(shell f="$(shell $(CC) -print-file-name=nano.specs 2>/dev/null)"; test "$$f" != "nano.specs" -a -f "$$f" && printf '%s' '-specs=nano.specs')
NOSYS_SPECS := $(shell f="$(shell $(CC) -print-file-name=nosys.specs 2>/dev/null)"; test "$$f" != "nosys.specs" -a -f "$$f" && printf '%s' '-specs=nosys.specs')

BUILD_DIR = build

# AT32 library paths
AT32_LIB = at32f403a_lib/libraries
AT32_DRV = $(AT32_LIB)/drivers
AT32_CMSIS = $(AT32_LIB)/cmsis/cm4
AT32_STARTUP = $(AT32_CMSIS)/device_support/startup/gcc

# Source files
# Default test program (override with: make -f Makefile.hwtest TEST=uartsniff)
TEST ?= hwtest
APP_SLOT ?= 0

VARIANT_SUFFIX =
C_DEFS =

C_SOURCES = \
	src/attic/$(TEST).c \
	src/at32f403a_407_clock.c \
	$(AT32_CMSIS)/device_support/system_at32f403a_407.c \
	$(AT32_DRV)/src/at32f403a_407_crm.c \
	$(AT32_DRV)/src/at32f403a_407_gpio.c \
	$(AT32_DRV)/src/at32f403a_407_flash.c \
	$(AT32_DRV)/src/at32f403a_407_misc.c \
	$(AT32_DRV)/src/at32f403a_407_xmc.c \
	$(AT32_DRV)/src/at32f403a_407_usart.c \
	$(AT32_DRV)/src/at32f403a_407_wdt.c

ASM_SOURCES = $(AT32_STARTUP)/startup_at32f403a_407.s

ifeq ($(APP_SLOT),1)
VARIANT_SUFFIX = _app
C_DEFS += -DHWTEST_APP_SLOT
C_SOURCES += src/drivers/dfu_boot.c
endif

# Include paths
C_INCLUDES = \
	-Iinclude \
	-Isrc \
	-Isrc/drivers \
	-I$(AT32_DRV)/inc \
	-I$(AT32_CMSIS)/device_support \
	-I$(AT32_CMSIS)/core_support \
	-I$(AT32_CMSIS)

# MCU flags
MCU = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard

# C flags
CFLAGS = $(MCU) $(C_INCLUDES) $(C_DEFS) -DAT32F403AVGT7 -Os -Wall -fdata-sections -ffunction-sections

# Linker
ifeq ($(APP_SLOT),1)
LDSCRIPT = ld/at32f403a_app.ld
FLASH_DFU_ADDR = 0x08004000
else
LDSCRIPT = $(AT32_STARTUP)/linker/AT32F403AxG_FLASH.ld
FLASH_DFU_ADDR = 0x08000000
endif

LDFLAGS = $(MCU) $(NANO_SPECS) $(NOSYS_SPECS) -T$(LDSCRIPT) -Wl,--gc-sections -Wl,-Map=$(BUILD_DIR)/hwtest.map,--cref

# Build targets
TARGET_NAME = $(TEST)$(VARIANT_SUFFIX)

all: $(BUILD_DIR)/$(TARGET_NAME).bin

OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s | $(BUILD_DIR)
	$(AS) -c $(MCU) $< -o $@

$(BUILD_DIR)/$(TARGET_NAME).elf: $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/$(TARGET_NAME).bin: $(BUILD_DIR)/$(TARGET_NAME).elf
	$(CP) -O binary $< $@
	@echo "Built: $@ ($$(wc -c < $@) bytes)"

$(BUILD_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR)

flash: $(BUILD_DIR)/$(TARGET_NAME).bin
ifeq ($(APP_SLOT),1)
	uv run ../scripts/hid_flash.py $<
else
	dfu-util -a 0 -d 2e3c:df11 -s $(FLASH_DFU_ADDR):leave -D $<
endif

flash-dfu: $(BUILD_DIR)/$(TARGET_NAME).bin
	dfu-util -a 0 -d 2e3c:df11 -s $(FLASH_DFU_ADDR):leave -D $<

.PHONY: all clean flash flash-dfu
